### ISSUE TITLE
oVirt Service error

### ISSUE THREAD

**Issue by Snegohod** [dkmstr/openuds#47]
Hello.
We a using oVirt 4.3.6 and try to add openuds as VDI broker.
But have some errors.
On OpenUDS 2.2 we can not connect to oVirt cluster

On OpenUDS master branch we have error when try add service oVirt/RHEV Linked Clone to oVirt Service provider
![error](https://user-images.githubusercontent.com/17003045/68836703-00848000-06cc-11ea-839b-3e9243edda4c.JPG)
After that we can not see and add any Datastore.

oVirt cluster settings
![ovirt](https://user-images.githubusercontent.com/17003045/68837182-134b8480-06cd-11ea-99db-72d329ad956a.JPG)

**services.log**
```
DEBUG 2019-11-14 09:00:43,439 ovirt getVms 166 oVirt VMS: [<ovirtsdk4.types.Vm object at 0x7f9f8c33bc50>, <ovirtsdk4.types.Vm object at 0x7f9f8c33bfd0>, <ovirtsdk4.types.Vm object at 0x7f9f8c33b358>, <ovirtsdk4.types.Vm object at 0x7f9f8c33b668>, <ovirtsdk4.types.Vm object at 0x7f9f8c33b080>]
DEBUG 2019-11-14 09:00:45,297 helpers getResources 22 Parameters received by getResources Helper: <QueryDict: {'cluster': ['88376e64-f0b9-11e9-a2b2-00163e3bb667'], 'ov': ['eJxNisEKg0AMBWH3eyqr6MWTJ8/FgvegwQa6iSTR9vNrEaQwl5n3ZCf1EdVIONbhKeYReSHGgthRGb1gkipsdghkjDBn4u4c4RVWMHuLzjGNpfraHZZ0Dhk+d8UVlHh5oO40ocUy/fqAWfb/3ASnjLL5eZhsAF4wNlXb1G1KF7er9P3JF2rSPzY='], 'ev': ['t-provider-1']}>
```

**uds.log**
```
DEBUG 2019-11-14 09:00:41,800 request getUser 167 User at Middleware: -20091204 User root (id:-20091204) from auth
DEBUG 2019-11-14 09:00:41,800 request getUser 167 User at Middleware: -20091204 User root (id:-20091204) from auth
DEBUG 2019-11-14 09:00:41,804 __init__ dispatch 105 REST request: providers (application/json; charset=utf8)
DEBUG 2019-11-14 09:00:41,804 __init__ dispatch 105 REST request: providers (application/json; charset=utf8)
DEBUG 2019-11-14 09:00:41,805 handlers __init__ 113 Data: <class 'uds.REST.methods.providers.Providers'> False True
DEBUG 2019-11-14 09:00:41,805 handlers __init__ 113 Data: <class 'uds.REST.methods.providers.Providers'> False True
DEBUG 2019-11-14 09:00:41,809 handlers getUser 295 REST : <django.contrib.sessions.backends.db.SessionStore object at 0x7f9f9422d320>
DEBUG 2019-11-14 09:00:41,809 handlers getUser 295 REST : <django.contrib.sessions.backends.db.SessionStore object at 0x7f9f9422d320>
DEBUG 2019-11-14 09:00:41,856 model doGet 801 method GET for Providers, ('69e209de-750d-5709-ac7e-7072eeb7ab63', 'services', 'gui', 'oVirtLinkedService')
DEBUG 2019-11-14 09:00:41,856 model doGet 801 method GET for Providers, ('69e209de-750d-5709-ac7e-7072eeb7ab63', 'services', 'gui', 'oVirtLinkedService')
DEBUG 2019-11-14 09:00:41,856 model processDetail 749 Processing detail providers for with params <QueryDict: {}>
DEBUG 2019-11-14 09:00:41,856 model processDetail 749 Processing detail providers for with params <QueryDict: {}>
DEBUG 2019-11-14 09:00:41,858 model get 387 Detail args for GET: ('gui', 'oVirtLinkedService')
DEBUG 2019-11-14 09:00:41,858 model get 387 Detail args for GET: ('gui', 'oVirtLinkedService')
DEBUG 2019-11-14 09:00:41,859 model __checkCustom 372 Checking custom method gui
DEBUG 2019-11-14 09:00:41,859 model __checkCustom 372 Checking custom method gui
DEBUG 2019-11-14 09:00:41,859 services getGui 247 getGui parameters: oVirt of type oVirtPlatform (id:1), oVirtLinkedService
DEBUG 2019-11-14 09:00:41,859 services getGui 247 getGui parameters: oVirt of type oVirtPlatform (id:1), oVirtLinkedService
DEBUG 2019-11-14 09:00:41,861 user_interface guiDescription 1009 Active language for theGui translation: en
DEBUG 2019-11-14 09:00:41,861 user_interface guiDescription 1009 Active language for theGui translation: en
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: ovirtVersion/4
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: ovirtVersion/4
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: host/engine.internet.local
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: host/engine.internet.local
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: username/admin@internal
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: username/admin@internal
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: password/password
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: password/password
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: maxPreparingServices/10
DEBUG 2019-11-14 09:00:41,861 user_interface serializeForm 929 serializing Key: maxPreparingServices/10
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 929 serializing Key: maxRemovingServices/5
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 929 serializing Key: maxRemovingServices/5
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 929 serializing Key: timeout/10
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 929 serializing Key: timeout/10
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 929 serializing Key: macsRange/52:54:00:00:00:00-52:54:00:FF:FF:FF
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 929 serializing Key: macsRange/52:54:00:00:00:00-52:54:00:FF:FF:FF
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 951 Arr, >>[b'ovirtVersion\x034', b'host\x03engine.internet.local', b'username\x03admin@internal', b'password\x03password', b'maxPreparingServices\x0310', b'maxRemovingServices\x035', b'timeout\x0310', b'macsRange\x0352:54:00:00:00:00-52:54:00:FF:FF:FF']<<
DEBUG 2019-11-14 09:00:41,862 user_interface serializeForm 951 Arr, >>[b'ovirtVersion\x034', b'host\x03engine.internet.local', b'username\x03admin@internal', b'password\x03password', b'maxPreparingServices\x0310', b'maxRemovingServices\x035', b'timeout\x0310', b'macsRange\x0352:54:00:00:00:00-52:54:00:FF:FF:FF']<<
DEBUG 2019-11-14 09:00:41,863 cache get 70 Requesting key "o-vmsengine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:41,863 cache get 70 Requesting key "o-vmsengine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:41,863 cache get 73 Key: bbdf782b196d61b757555e94603615c7
DEBUG 2019-11-14 09:00:41,863 cache get 73 Key: bbdf782b196d61b757555e94603615c7
DEBUG 2019-11-14 09:00:44,548 cache get 70 Requesting key "o-clustersengine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:44,548 cache get 70 Requesting key "o-clustersengine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:44,548 cache get 73 Key: f08ebfcef9e14bf18549274abc519bbf
DEBUG 2019-11-14 09:00:44,548 cache get 73 Key: f08ebfcef9e14bf18549274abc519bbf
DEBUG 2019-11-14 09:00:44,803 user_interface guiDescription 1018 cluster ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329320>
DEBUG 2019-11-14 09:00:44,803 user_interface guiDescription 1018 cluster ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329320>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 datastore ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329c18>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 datastore ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329c18>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 minSpaceGB ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c329ef0>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 minSpaceGB ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c329ef0>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 machine ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329198>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 machine ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329198>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 memory ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c3290b8>
DEBUG 2019-11-14 09:00:44,804 user_interface guiDescription 1018 memory ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c3290b8>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 memoryGuaranteed ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c3296a0>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 memoryGuaranteed ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c3296a0>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 usb ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329080>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 usb ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329080>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 display ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329438>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 display ### <uds.core.ui.user_interface.gui.ChoiceField object at 0x7f9f8c329438>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 baseName ### <uds.core.ui.user_interface.gui.TextField object at 0x7f9f8c329518>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 baseName ### <uds.core.ui.user_interface.gui.TextField object at 0x7f9f8c329518>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 lenName ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c329a90>
DEBUG 2019-11-14 09:00:44,805 user_interface guiDescription 1018 lenName ### <uds.core.ui.user_interface.gui.NumericField object at 0x7f9f8c329a90>
DEBUG 2019-11-14 09:00:44,806 user_interface guiDescription 1018 ov ### <uds.core.ui.user_interface.gui.HiddenField object at 0x7f9f8c329e48>
DEBUG 2019-11-14 09:00:44,806 user_interface guiDescription 1018 ov ### <uds.core.ui.user_interface.gui.HiddenField object at 0x7f9f8c329e48>
DEBUG 2019-11-14 09:00:44,806 user_interface guiDescription 1018 ev ### <uds.core.ui.user_interface.gui.HiddenField object at 0x7f9f8c329588>
DEBUG 2019-11-14 09:00:44,806 user_interface guiDescription 1018 ev ### <uds.core.ui.user_interface.gui.HiddenField object at 0x7f9f8c329588>
DEBUG 2019-11-14 09:00:44,806 user_interface guiDescription 1021 >>>>>>>>>>>> Gui Description: Base Service Provider -- [{'name': 'cluster', 'gui': {'length': 32, 'required': True, 'label': 'Cluster', 'defvalue': '', 'rdonly': False, 'order': 100, 'tooltip': 'Cluster to contain services', 'type': 'choice', 'value': '', 'values': [{'id': '88376e64-f0b9-11e9-a2b2-00163e3bb667', 'text': 'Default'}], 'fills': {'callbackName': 'ovFillResourcesFromCluster', 'parameters': ['cluster', 'ov', 'ev']}}, 'value': ''}, {'name': 'datastore', 'gui': {'length': 32, 'required': True, 'label': 'Datastore Domain', 'defvalue': '', 'rdonly': False, 'order': 101, 'tooltip': 'Datastore domain where to publish and put incrementals', 'type': 'choice', 'value': '', 'values': []}, 'value': ''}, {'name': 'minSpaceGB', 'gui': {'length': 3, 'required': True, 'label': 'Reserved Space', 'defvalue': '32', 'rdonly': False, 'order': 102, 'tooltip': 'Minimal free space in GB', 'type': 'numeric', 'value': '', 'minValue': 0, 'maxValue': 987654321}, 'value': ''}, {'name': 'machine', 'gui': {'length': 32, 'required': True, 'label': 'Base Machine', 'defvalue': '', 'rdonly': False, 'order': 110, 'tooltip': 'Service base machine', 'type': 'choice', 'value': '', 'tab': 'Machine', 'values': [{'id': 'ff9af7c7-96cb-404b-84e9-21d9380eb6a3', 'text': 'Elasticsearch'}, {'id': 'a530d851-6c8f-4f55-93a6-5f8337e73824', 'text': 'HostedEngine'}, {'id': '375e55e7-28d2-4817-91cf-78d08fba911c', 'text': 'OpenUDS'}, {'id': '97fa77f3-9610-4bdc-bbfe-735d7ae3253a', 'text': 'Suricata'}, {'id': 'b782cf17-7825-4342-a373-d3ebbacca7b5', 'text': 'test'}]}, 'value': ''}, {'name': 'memory', 'gui': {'length': 4, 'required': True, 'label': 'Memory (Mb)', 'defvalue': '512', 'rdonly': False, 'order': 111, 'tooltip': 'Memory assigned to machines', 'type': 'numeric', 'value': '', 'tab': 'Machine', 'minValue': 0, 'maxValue': 987654321}, 'value': ''}, {'name': 'memoryGuaranteed', 'gui': {'length': 4, 'required': True, 'label': 'Memory Guaranteed (Mb)', 'defvalue': '256', 'rdonly': False, 'order': 112, 'tooltip': 'Physical memory guaranteed to machines', 'type': 'numeric', 'value': '', 'tab': 'Machine', 'minValue': 0, 'maxValue': 987654321}, 'value': ''}, {'name': 'usb', 'gui': {'length': 32, 'required': False, 'label': 'USB', 'defvalue': '1', 'rdonly': False, 'order': 113, 'tooltip': 'Enable usb redirection for SPICE', 'type': 'choice', 'value': '', 'tab': 'Machine', 'values': [{'id': 'disabled', 'text': 'disabled'}, {'id': 'native', 'text': 'native'}]}, 'value': ''}, {'name': 'display', 'gui': {'length': 32, 'required': False, 'label': 'Display', 'defvalue': '1', 'rdonly': False, 'order': 114, 'tooltip': 'Display type (only for administration purposes)', 'type': 'choice', 'value': '', 'tab': 'Machine', 'values': [{'id': 'spice', 'text': 'Spice'}, {'id': 'vnc', 'text': 'Vnc'}]}, 'value': ''}, {'name': 'baseName', 'gui': {'length': 32, 'required': True, 'label': 'Machine Names', 'defvalue': '', 'rdonly': False, 'order': 115, 'tooltip': 'Base name for clones from this machine', 'type': 'text', 'value': '', 'tab': 'Machine', 'multiline': 0}, 'value': ''}, {'name': 'lenName', 'gui': {'length': 1, 'required': True, 'label': 'Name Length', 'defvalue': '5', 'rdonly': False, 'order': 116, 'tooltip': 'Size of numeric part for the names of these machines (between 3 and 6)', 'type': 'numeric', 'value': '', 'tab': 'Machine', 'minValue': 987654321, 'maxValue': 987654321}, 'value': ''}, {'name': 'ov', 'gui': {'length': 32, 'required': False, 'label': '', 'defvalue': 'eJxNisEKg0AMBWH3eyqr6MWTJ8/FgvegwQa6iSTR9vNrEaQwl5n3ZCf1EdVIONbhKeYReSHGgthRGb1gkipsdghkjDBn4u4c4RVWMHuLzjGNpfraHZZ0Dhk+d8UVlHh5oO40ocUy/fqAWfb/3ASnjLL5eZhsAF4wNlXb1G1KF7er9P3JF2rSPzY=', 'rdonly': False, 'order': 0, 'tooltip': '', 'type': 'hidden', 'value': None}, 'value': ''}, {'name': 'ev', 'gui': {'length': 32, 'required': False, 'label': '', 'defvalue': 't-provider-1', 'rdonly': False, 'order': 0, 'tooltip': '', 'type': 'hidden', 'value': None}, 'value': ''}]
DEBUG 2019-11-14 09:00:44,806 user_interface guiDescription 1021 >>>>>>>>>>>> Gui Description: Base Service Provider -- [{'name': 'cluster', 'gui': {'length': 32, 'required': True, 'label': 'Cluster', 'defvalue': '', 'rdonly': False, 'order': 100, 'tooltip': 'Cluster to contain services', 'type': 'choice', 'value': '', 'values': [{'id': '88376e64-f0b9-11e9-a2b2-00163e3bb667', 'text': 'Default'}], 'fills': {'callbackName': 'ovFillResourcesFromCluster', 'parameters': ['cluster', 'ov', 'ev']}}, 'value': ''}, {'name': 'datastore', 'gui': {'length': 32, 'required': True, 'label': 'Datastore Domain', 'defvalue': '', 'rdonly': False, 'order': 101, 'tooltip': 'Datastore domain where to publish and put incrementals', 'type': 'choice', 'value': '', 'values': []}, 'value': ''}, {'name': 'minSpaceGB', 'gui': {'length': 3, 'required': True, 'label': 'Reserved Space', 'defvalue': '32', 'rdonly': False, 'order': 102, 'tooltip': 'Minimal free space in GB', 'type': 'numeric', 'value': '', 'minValue': 0, 'maxValue': 987654321}, 'value': ''}, {'name': 'machine', 'gui': {'length': 32, 'required': True, 'label': 'Base Machine', 'defvalue': '', 'rdonly': False, 'order': 110, 'tooltip': 'Service base machine', 'type': 'choice', 'value': '', 'tab': 'Machine', 'values': [{'id': 'ff9af7c7-96cb-404b-84e9-21d9380eb6a3', 'text': 'Elasticsearch'}, {'id': 'a530d851-6c8f-4f55-93a6-5f8337e73824', 'text': 'HostedEngine'}, {'id': '375e55e7-28d2-4817-91cf-78d08fba911c', 'text': 'OpenUDS'}, {'id': '97fa77f3-9610-4bdc-bbfe-735d7ae3253a', 'text': 'Suricata'}, {'id': 'b782cf17-7825-4342-a373-d3ebbacca7b5', 'text': 'test'}]}, 'value': ''}, {'name': 'memory', 'gui': {'length': 4, 'required': True, 'label': 'Memory (Mb)', 'defvalue': '512', 'rdonly': False, 'order': 111, 'tooltip': 'Memory assigned to machines', 'type': 'numeric', 'value': '', 'tab': 'Machine', 'minValue': 0, 'maxValue': 987654321}, 'value': ''}, {'name': 'memoryGuaranteed', 'gui': {'length': 4, 'required': True, 'label': 'Memory Guaranteed (Mb)', 'defvalue': '256', 'rdonly': False, 'order': 112, 'tooltip': 'Physical memory guaranteed to machines', 'type': 'numeric', 'value': '', 'tab': 'Machine', 'minValue': 0, 'maxValue': 987654321}, 'value': ''}, {'name': 'usb', 'gui': {'length': 32, 'required': False, 'label': 'USB', 'defvalue': '1', 'rdonly': False, 'order': 113, 'tooltip': 'Enable usb redirection for SPICE', 'type': 'choice', 'value': '', 'tab': 'Machine', 'values': [{'id': 'disabled', 'text': 'disabled'}, {'id': 'native', 'text': 'native'}]}, 'value': ''}, {'name': 'display', 'gui': {'length': 32, 'required': False, 'label': 'Display', 'defvalue': '1', 'rdonly': False, 'order': 114, 'tooltip': 'Display type (only for administration purposes)', 'type': 'choice', 'value': '', 'tab': 'Machine', 'values': [{'id': 'spice', 'text': 'Spice'}, {'id': 'vnc', 'text': 'Vnc'}]}, 'value': ''}, {'name': 'baseName', 'gui': {'length': 32, 'required': True, 'label': 'Machine Names', 'defvalue': '', 'rdonly': False, 'order': 115, 'tooltip': 'Base name for clones from this machine', 'type': 'text', 'value': '', 'tab': 'Machine', 'multiline': 0}, 'value': ''}, {'name': 'lenName', 'gui': {'length': 1, 'required': True, 'label': 'Name Length', 'defvalue': '5', 'rdonly': False, 'order': 116, 'tooltip': 'Size of numeric part for the names of these machines (between 3 and 6)', 'type': 'numeric', 'value': '', 'tab': 'Machine', 'minValue': 987654321, 'maxValue': 987654321}, 'value': ''}, {'name': 'ov', 'gui': {'length': 32, 'required': False, 'label': '', 'defvalue': 'eJxNisEKg0AMBWH3eyqr6MWTJ8/FgvegwQa6iSTR9vNrEaQwl5n3ZCf1EdVIONbhKeYReSHGgthRGb1gkipsdghkjDBn4u4c4RVWMHuLzjGNpfraHZZ0Dhk+d8UVlHh5oO40ocUy/fqAWfb/3ASnjLL5eZhsAF4wNlXb1G1KF7er9P3JF2rSPzY=', 'rdonly': False, 'order': 0, 'tooltip': '', 'type': 'hidden', 'value': None}, 'value': ''}, {'name': 'ev', 'gui': {'length': 32, 'required': False, 'label': '', 'defvalue': 't-provider-1', 'rdonly': False, 'order': 0, 'tooltip': '', 'type': 'hidden', 'value': None}, 'value': ''}]
DEBUG 2019-11-14 09:00:44,809 request _process_response 86 Deleting 140323370309376
DEBUG 2019-11-14 09:00:44,809 request _process_response 86 Deleting 140323370309376
INFO 2019-11-14 09:00:44,810 basehttp log_message 154 "GET /uds/rest/providers/69e209de-750d-5709-ac7e-7072eeb7ab63/services/gui/oVirtLinkedService HTTP/1.1" 200 4997
DEBUG 2019-11-14 09:00:45,271 request getUser 167 User at Middleware: -20091204 User root (id:-20091204) from auth
DEBUG 2019-11-14 09:00:45,271 request getUser 167 User at Middleware: -20091204 User root (id:-20091204) from auth
DEBUG 2019-11-14 09:00:45,272 __init__ dispatch 105 REST request: gui/callback (application/json; charset=utf8)
DEBUG 2019-11-14 09:00:45,272 __init__ dispatch 105 REST request: gui/callback (application/json; charset=utf8)
DEBUG 2019-11-14 09:00:45,273 handlers __init__ 113 Data: <class 'uds.REST.methods.gui_callback.Callback'> False True
DEBUG 2019-11-14 09:00:45,273 handlers __init__ 113 Data: <class 'uds.REST.methods.gui_callback.Callback'> False True
DEBUG 2019-11-14 09:00:45,275 handlers getUser 295 REST : <django.contrib.sessions.backends.db.SessionStore object at 0x7f9f953839e8>
DEBUG 2019-11-14 09:00:45,275 handlers getUser 295 REST : <django.contrib.sessions.backends.db.SessionStore object at 0x7f9f953839e8>
DEBUG 2019-11-14 09:00:45,299 cache get 70 Requesting key "o-cluster88376e64-f0b9-11e9-a2b2-00163e3bb667engine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:45,299 cache get 70 Requesting key "o-cluster88376e64-f0b9-11e9-a2b2-00163e3bb667engine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:45,299 cache get 73 Key: 2fd3bcddb817d61cde6975080bf5bfa9
DEBUG 2019-11-14 09:00:45,299 cache get 73 Key: 2fd3bcddb817d61cde6975080bf5bfa9
DEBUG 2019-11-14 09:00:45,301 cache get 80 value: gAN9cQAoWAQAAABuYW1lcQFYBwAAAERlZmF1bHRxAlgCAAAAaWRxA1gkAAAAODgzNzZlNjQtZjBi
OS0xMWU5LWEyYjItMDAxNjNlM2JiNjY3cQRYDQAAAGRhdGFjZW50ZXJfaWRxBVgkAAAAODgzMDNl
YzgtZjBiOS0xMWU5LWIwYTEtMDAxNjNlM2JiNjY3cQZ1Lg==

DEBUG 2019-11-14 09:00:45,301 cache get 80 value: gAN9cQAoWAQAAABuYW1lcQFYBwAAAERlZmF1bHRxAlgCAAAAaWRxA1gkAAAAODgzNzZlNjQtZjBi
OS0xMWU5LWEyYjItMDAxNjNlM2JiNjY3cQRYDQAAAGRhdGFjZW50ZXJfaWRxBVgkAAAAODgzMDNl
YzgtZjBiOS0xMWU5LWIwYTEtMDAxNjNlM2JiNjY3cQZ1Lg==

DEBUG 2019-11-14 09:00:45,302 cache get 70 Requesting key "o-dc88303ec8-f0b9-11e9-b0a1-00163e3bb667engine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:45,302 cache get 70 Requesting key "o-dc88303ec8-f0b9-11e9-b0a1-00163e3bb667engine.internet.localadmin@internalpassword10" for cache "t-provider-1"
DEBUG 2019-11-14 09:00:45,302 cache get 73 Key: 00e30191d60e63cb2bf0477540426946
DEBUG 2019-11-14 09:00:45,302 cache get 73 Key: 00e30191d60e63cb2bf0477540426946
DEBUG 2019-11-14 09:00:45,304 cache get 91 key not found: o-dc88303ec8-f0b9-11e9-b0a1-00163e3bb667engine.internet.localadmin@internalpassword10
DEBUG 2019-11-14 09:00:45,304 cache get 91 key not found: o-dc88303ec8-f0b9-11e9-b0a1-00163e3bb667engine.internet.localadmin@internalpassword10
ERROR 2019-11-14 09:00:45,357 __init__ dispatch 165 Error processing request
Traceback (most recent call last):
  File "/root/openuds/server/src/uds/REST/__init__.py", line 144, in dispatch
    response = operation()
  File "/root/openuds/server/src/uds/REST/methods/gui_callback.py", line 55, in get
    return gui.callbacks[self._args[0]](self._params)
  File "/root/openuds/server/src/uds/services/OVirt/helpers.py", line 32, in getResources
    for storage in provider.getDatacenterInfo(ci['datacenter_id'])['storage']:
  File "/root/openuds/server/src/uds/services/OVirt/provider.py", line 248, in getDatacenterInfo
    return self.__getApi().getDatacenterInfo(datacenterId, force)
  File "/root/openuds/server/src/uds/services/OVirt/client/ovirt.py", line 310, in getDatacenterInfo
    datacenter_service = api.system_service().data_centers_service().service(datacenterId.encode())
  File "/usr/local/lib64/python3.6/site-packages/ovirtsdk4/services.py", line 6149, in service
    index = path.find('/')
TypeError: a bytes-like object is required, not 'str'
ERROR 2019-11-14 09:00:45,357 __init__ dispatch 165 Error processing request
Traceback (most recent call last):
  File "/root/openuds/server/src/uds/REST/__init__.py", line 144, in dispatch
    response = operation()
  File "/root/openuds/server/src/uds/REST/methods/gui_callback.py", line 55, in get
    return gui.callbacks[self._args[0]](self._params)
  File "/root/openuds/server/src/uds/services/OVirt/helpers.py", line 32, in getResources
    for storage in provider.getDatacenterInfo(ci['datacenter_id'])['storage']:
  File "/root/openuds/server/src/uds/services/OVirt/provider.py", line 248, in getDatacenterInfo
    return self.__getApi().getDatacenterInfo(datacenterId, force)
  File "/root/openuds/server/src/uds/services/OVirt/client/ovirt.py", line 310, in getDatacenterInfo
    datacenter_service = api.system_service().data_centers_service().service(datacenterId.encode())
  File "/usr/local/lib64/python3.6/site-packages/ovirtsdk4/services.py", line 6149, in service
    index = path.find('/')
TypeError: a bytes-like object is required, not 'str'
DEBUG 2019-11-14 09:00:45,358 request _process_response 86 Deleting 140323370309376
DEBUG 2019-11-14 09:00:45,358 request _process_response 86 Deleting 140323370309376
ERROR 2019-11-14 09:00:45,359 log log_response 228 Internal Server Error: /uds/rest/gui/callback/ovFillResourcesFromCluster
ERROR 2019-11-14 09:00:45,359 basehttp log_message 154 "GET /uds/rest/gui/callback/ovFillResourcesFromCluster?cluster=88376e64-f0b9-11e9-a2b2-00163e3bb667&ov=eJxNisEKg0AMBWH3eyqr6MWTJ8%2FFgvegwQa6iSTR9vNrEaQwl5n3ZCf1EdVIONbhKeYReSHGgthRGb1gkipsdghkjDBn4u4c4RVWMHuLzjGNpfraHZZ0Dhk%2Bd8UVlHh5oO40ocUy%2FfqAWfb%2F3ASnjLL5eZhsAF4wNlXb1G1KF7er9P3JF2rSPzY%3D&ev=t-provider-1 HTTP/1.1" 500 42
```

**Comment by dkmstr** [comment]
Hi,
Thanks for the detailed information! :)
The "master" version is currently under heavy development and is not 100% funtional. We have migrated the ovirt platform to this, but have not been tested, so we do not recommend you to use it right now.

Try with 2.2 version, that is working ocrrectly with ovirt 4, but also.

Please also note that 2.2 uses python 2.7 and 3.0 uses python 3.7 (we have not support for 3.6 or newer vertsions for this release) or newer, anyway, we will use your information when we reach the testing part for oVirt.

Meanwhile, use python 2.7 with 2.2 release pleas, and let me know if you have any issues (i have a 4.2 running with UDS 2.2).
